---
# Here is the place for variable assertions before the actual installation process

- name: Assert binary architecture was detected
  ansible.builtin.assert:
    that: release_binary_arch not in (None, omit)
    fail_msg: "Release binary architecture not set!"
    success_msg: Release binary architecture is {{ release_binary_arch }}
  when: ntfy_installation_mode == "binary"
