---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include stevenengland.ntfy_ansible_role"
      ansible.builtin.include_role:
        name: "stevenengland.ntfy_ansible_role"
