---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Include stevenengland.ntfy
      ansible.builtin.include_role:
        name: "stevenengland.ntfy"
      vars:
        ntfy_installation_mode: package_repo
